[package]
name = "evdev"
version = "0.11.0-alpha.2"
authors = ["Corey Richardson <corey@octayn.net>"]
description = "evdev interface for Linux"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/cmr/evdev"
documentation = "https://docs.rs/evdev"
edition = "2018"

[dependencies]
bitflags = "1.2"
libc = "0.2.22"
fixedbitset = "0.3.2"
num-derive = "0.3.3"
num-traits = { version = "0.2", default-features = false }
nix = "0.19.0"
thiserror = "1.0.24"
