[package]
name = "evtest_tokio"
version = "0.1.0"
authors = ["Noah <33094578+coolreader18@users.noreply.github.com>"]
edition = "2018"

[dependencies]
evdev = { path = "../..", features = ["tokio"] }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
futures-util = "0.3"
